

info:
  app:
    name: '@project.name@'
    version: '@project.version@'

spring:
  application:
    name: '@project.name@'

management:
  info:
    env:
      enabled: true
  endpoints:
    web:
      exposure:
        include: "*"
      base-path: /monitoring
grpc:
  server:
    port: 9001
