---
apiVersion: v1
kind: Service
metadata:
  name: hotel-availability-pad
  namespace: beta-app
spec:
  type: ClusterIP
  ports:
    - port: 8088
      targetPort: 8088
  selector:
    app.kubernetes.io/name: hotel-availability-pad